from django import forms

class AssessmentForm(forms.Form):
	age = forms.IntegerField()
	number_of_sexual_partners = forms.IntegerField()
	first_sexual_intercourse = forms.IntegerField()
	num_of_pregnancies = forms.IntegerField()
	smokes = forms.BooleanField(required=False)
	smokes_years = forms.IntegerField()
	smokes_packs_per_year = forms.IntegerField()
	hormonal_contraceptives = forms.BooleanField(required=False)
	hormonal_contraceptives_years = forms.IntegerField()
	iud = forms.BooleanField(required=False)
	iud_years = forms.IntegerField()
	stds = forms.BooleanField(required=False)
	stds_number = forms.IntegerField()
	condylomatosis = forms.BooleanField(required=False)
	cervical_condylomatosis = forms.BooleanField(required=False)
	vaginal_condylomatosis = forms.BooleanField(required=False)
	vulvo_perineal_condylomatosis = forms.BooleanField(required=False)
	syphilis = forms.BooleanField(required=False)
	pelvic_inflammatory_disease = forms.BooleanField(required=False)
	genital_herpes = forms.BooleanField(required=False)
	molluscum_contagiosum = forms.BooleanField(required=False)
	aids = forms.BooleanField(required=False)
	hiv = forms.BooleanField(required=False)
	hepatitis_b = forms.BooleanField(required=False)
	hpv = forms.BooleanField(required=False)
	number_of_diagnosis  = forms.IntegerField()
	dx_cin = forms.BooleanField(required = False)
	dx_hpv = forms.BooleanField(required = False)