from django import forms

class AssessmentForm(forms.Form):
	age = forms.IntegerField()
	number_of_sexual_partners = forms.IntegerField()
	first_sexual_intercourse = forms.IntegerField()
	num_of_pregnancies = forms.IntegerField()
	smokes = forms.BooleanField()
	smokes_years = forms.IntegerField()
	smokes_packs_per_year = forms.IntegerField()
	hormonal_contraceptives = forms.BooleanField()
	hormonal_contraceptives_years = forms.IntegerField()
	iud = forms.BooleanField()
	iud_years = forms.IntegerField()
	stds = forms.BooleanField()
	stds_number = forms.IntegerField()
	condylomatosis = forms.BooleanField()
	cervical_condylomatosis = forms.BooleanField()
	vaginal_condylomatosis = forms.BooleanField()
	vulvo_perineal_condylomatosis = forms.BooleanField()
	syphilis = forms.BooleanField()
	pelvic_inflammatory_disease = forms.BooleanField()
	genital_herpes = forms.BooleanField()
	molluscum_contagiosum = forms.BooleanField()
	aids = forms.BooleanField()
	hiv = forms.BooleanField()
	hepatitis_b = forms.BooleanField()
	hpv = forms.BooleanField()
	number_of_diagnosis  = forms.IntegerField()
	hinselmann = forms.BooleanField()
	schiller = forms.BooleanField()
	citology = forms.BooleanField()